### ISSUE TITLE
WALL_SIGN

### ISSUE THREAD

**Issue by iamadcat** [FabioZumbi12/RedProtect#100]
i always used to set the cmd 'allow-place / allow-break' to wall_sign in some regions.

but after updated, i can't use like this. it keeps saying "you can't interact with this".

how can i make the user only can place wall_sign?

**Comment by iamadcat** [comment]
25 days :(

**Comment by CloudeLecaw** [comment]
have u tried the flags for that?

sign: 
To be compatible with other plugins sings and deny bugs like xp sign banks. If you use CHestShop on your server, set the flag in this region to true.
Usage: /rp flag sign [true/false]
Permission: redprotect.admin.flag.sign

**Comment by FabioZumbi12** [comment]
That explanation sesm to solve. Have you tested @iamadcat ?

**Comment by JuaneXec** [comment]
Hi,
I have been strugling with this issue for some time now and still can't get it solver, I think there might be a compatibility issue or something.

The thing is that even for allow-enter-items flag there seems to be aproblem with names because I set to that flag the oak_sign and even with the same objet in my hand used to set the flag in the gui I am reveiving a message that I need an OAK_SIGN to enter this region. I've tried all kind of sign name variants, upper case, lower case, but still the issue.

Can someone help me with an example of how I should write the flag syntax or what could be happening?

I'm using Paper 1.14.4
