### ISSUE TITLE
Bug with flag smart-door

### ISSUE THREAD

**Issue by aurel85** [FabioZumbi12/RedProtect#114]
Since the change to 1.11 (last version of RedProtect and PaperSpigot # 960) this flag no longer works. No owner of the claim can open the iron doors with his hands as he could do it in 1.10, sometimes he can succeed with a block in his hand but it does not work all the time. Am I the only one?

**Comment by CloudeLecaw** [comment]
Since 1.11 u cant open iron Trapdoors and iron doors with "No Item in hand" i know whatu mean.

if u are to far away with a block in gand u activate the Iron trapdoor/iron door and place the block next to it.
to avoid this sstand before the iron door directly with the block in hand, stand on the iron trapdoor with a block in hand.
then they open and close.

and your right. this has not to do with Paperspigot. The same happens in Spigot 1.11.
maybe they changed something from the code....like mostly..

**Comment by FabioZumbi12** [comment]
Yes,

Seems to be some problem with 1.11.

I tyed all ways to open/close iron doors/double doors using code but cant. I tested in 1.7, 1.8, 1.9, 1.10 and worked like a charm in all.

I will wait and see if this is a temporary issue with minecraft.

**Comment by FabioZumbi12** [comment]
Its a Minecraft bug :/
