### ISSUE TITLE
All my regions is deleted

### ISSUE THREAD

**Issue by kasdo** [FabioZumbi12/RedProtect#190]
RedProtect 137
Version: 1.10.2
Last version of sponge

Errors in log:
Redprotect: [Error during save database file for world WorldServer{LevelName=world, DimensionId=0, DimensionType=minecraft:overworld}: ]

No other errors

**Comment by FabioZumbi12** [comment]
This error is not enought. Paste the whole error on hastebin.com, not here.

**Comment by kasdo** [comment]
https://hastebin.com/xexuqidaxe.md

**Comment by kasdo** [comment]
If backup just this https://hastebin.com/ugojureboh.scala
What is wrong with backup?

**Comment by FabioZumbi12** [comment]
This seems you are with your hd full or with not write access. Theres nothig i can do about this, only you. Backups is experimental on sponge :S

**Comment by kasdo** [comment]
hd full? What its mean?
I dont do nothing... They just deleted...

**Comment by FabioZumbi12** [comment]
Yeah. Again... considering your other issues, you have some problens with your machine. If you server machine is really good and you think the issue is RedProtect, you can try other antigrief issues because i cant with issues that are you having.

hd full, i mean your server hard drive have no available space.

**Comment by kasdo** [comment]
Fabio! My region cant save coz I install mod ironchests. Can u fix this?
