### ISSUE TITLE
Wand and Border Blocks causing issues. (SpongeVanilla 1.12.2)

### ISSUE THREAD

**Issue by Mine15029** [FabioZumbi12/RedProtect#233]
_Put if is the **Spigot** or **Sponge** version._  
Platform:  **SpongeVanilla 1.12.2-7.0.0-BETA-386**

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  **RedProtect-7.3.0-b60-Universal.jar**

_Your server Minecraft version_  
Minecraft version: **1.12.2**

_Issue or Suggestion?_  
What you want?: **Issue**

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description: Using the wand to select the area, right clicking causes multiple selections to occur, spamming the chat. Furthermore, if you select the area by first left clicking and then right clicking, the border blocks are able to be broken and the glowstone dust is able to be picked up. If you first right click and then left click, the border blocks work fine. There is nothing that appears in the console which would suggest an error.

**Comment by ryantheleach** [comment]
FYI, if you use https://github.com/SpongePowered/SpongeAPI/blob/421703e3f330aa0ab630c1deab4a434f637809f2/src/main/java/org/spongepowered/api/effect/Viewer.java#L239 You are able to send 'fake blocks' to the client.

This means that there is 0 chance of duping the blocks even if things were to fail. Without sending fake blocks, you must be having to listen to a ton of stuff in order to recognize fakes and cancel the breaks.

**Comment by FabioZumbi12** [comment]
Thanks, changed to this way and now is fixed <3
