### ISSUE TITLE
Error with / rp help 3 in the German language file

### ISSUE THREAD

**Issue by Blueeyestar** [FabioZumbi12/RedProtect#239]
_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Paper Spigot

_Inform you RedProtect jar name like **RedProtect-Spigot-7.0.3.jar**._  
Jar version:  RedProtect 7.3.0 b68

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  **Error with / rp help 3 in the German language file. / rp edit-rent is not working.
Missing language string for cmdmanager.translation.eco.buy, Missing language string for cmdmanager.translation.eco.buy.alias**

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:

**Comment by FabioZumbi12** [comment]
I think is refering to #238 ?

**Comment by Blueeyestar** [comment]
No, it also comes when you generate it fresh without having it corrected

**Comment by SchattenritterX** [comment]
I looked in all language Files and only the Russian and German language File are having the cmdmanager.translation.**ECO**.buy/sell line. And in the Russian translation you'll get the translation for

- `/rp buy|b `and `/rp sell|s` - Both commands seems "outdated". /rp b is showing the border and /rp s doesn't exists. And /rp buy and /rp sell are already got translated with lines:

```
cmdmanager.help.sell
cmdmanager.help.buy
```

So you having the translation in Russian and German double. In both is the `cmdmanager.help.sell` Line still English and isn't translated.

I think the Error appears only in the German language file the Translator was using `{cmd}|{alias} `instead of `buy|b` and `sell|s`

To fix it I've deleted in the German language file the line 9
`cmdmanager.help.eco.buy=&3/rp {cmd}|{alias} &r- &b Kauft die Region in der du dich befndest.`

renamend Line 412
`cmdmanager.help.eco.sell=&3/rp {cmd}|{alias} [leader/value] [value] &r- &bVerkauft die Region, mit der Option das Oberhaupt festzulegen.`
to
`cmdmanager.help.sell=&3/rp {cmd}|{alias} [leader/value] [value] &r- &bVerkauft die Region, mit der Option das Oberhaupt festzulegen.`

and deleted the line 284
`cmdmanager.help.sell=&3/rp {cmd}|{alias} [leader/value] [value] &r- &b Sell your region, with option to set the leader.`

btw: The PT-BR Language file doesn't get downloaded.
`# Available: EN-US, PT-BR, ZH-CN, DE-DE, RU-RU`

**Comment by FabioZumbi12** [comment]
Acentuation depends of your Java/machine conding too. I am using pt-br and i having no problems with special characters. And about other languages, all is user maded and probally theres some lines outdated and some wrongs too.

The english is the reference for all others. If one line is not present in a language file, the english will be used.
