### ISSUE TITLE
Players cant build

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#24]
With Version 6.5.1 the Regions now laoding

but players cant interact in their regions, seems like it doesnt matter if they are
leader, admin or members...
was that wanted?

**Comment by FabioZumbi12** [comment]
After that problem with database, see if the players are added as leader on regions. If you can, send me your database file or check this.

**Comment by CloudeLecaw** [comment]
i added the extansion,txt because im not allowed to update yml files.
can u take a look at it?
on /rp info all is shown correct
[data_NSH.yml.txt](https://github.com/FabioZumbi12/RedProtect/files/149475/data_NSH.yml.txt)

**Comment by FabioZumbi12** [comment]
Really i dont know what can be! The players seems is added on regions correctly. Please give me this infos:

You, as op, can Interact on regions?
Dont get any erros on console?
What message show for players that cant Interact (if show).
Whit one of this players online, can you enable the debug-messages and copy/paste the changelog of the trys of this player to interact on region?
You tryed to running on a new server (local for tests) with default configurations and default flags??

This is weird because i think, no other user of RP have this problem.

**Comment by CloudeLecaw** [comment]
i as Op and players with the admin permission can interact no matter what position they are.
i dont got errors from the console :\
The leaders and admins can open and change the flag guis
The message "you cant Interact here" whent he palyers tried to interact in the region.

Edit: 28.02. With Version 6.5.2 this error sems to be gone now. now it works =)
So please close this issues :)
