### ISSUE TITLE
Selections with WorldEdit(CUI)

### ISSUE THREAD

**Issue by iBars** [FabioZumbi12/RedProtect#282]
Platform: Sponge
Minecraft version:  1.12.2

Issue and suggestion:

Add ability to use WorldEdit selection for regions. We using WorldEditCUI on our server to view current selection, and it's more efficient than glitched glowstone implemented in RedProtect. It will make life better for players. Thank you so much

**Comment by CloudeLecaw** [comment]
What ever WorldEditCUI is it is no bigger Plugin. 

i can understand you, but the problem is if u allow your players using the RedProtectwand for RegionCreation then you would also allow them to use the WorldEditWand that may could be missused.

So pls Fabio, If u should think About adding the WorldEditWand as Selection tool pls make it just optional.

WorldEdit would be a HardDepency then and may not all servers wanne use WorldEdit even if it one of the may most used and well known Plugins :-p

**Comment by FabioZumbi12** [comment]
I've added for sponge, but need some testing

![image](https://user-images.githubusercontent.com/5833818/44303686-c9cf8680-a31d-11e8-8d76-2d90893da8c5.png)
The command is `/rp swe` (select-we). This will make a selection on worldedit based on the region you is in.
