### ISSUE TITLE
[Bug] - Claim Size is false calculated

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#325]
In my Setup i defined a claimable blocksize of 12000 Blocks
i marked a region with 120x120 Blocks - this would be 14000 normaly...
but this is what RP tells me

![image](https://user-images.githubusercontent.com/12080017/45129907-9ba7ce80-b186-11e8-96b4-84dcb6f469fe.png)

You see that the size is more then the double ...?
Also when i add Blocks on Y (higher position) then more blocks got added...
why?

Problem is more and more player on the server report they tried to claim a 120x100 region with the wand tool but cant claim it because RP tells them they are over 24xxx blocks...

Is this a bug in the calculation?

**Comment by CloudeLecaw** [comment]
In Discord a user names Darkilien asked me just to try it with the two permissions resprotect.user and redprotect.own.claim
I gave this two permissions to my testgroup. For testing we try to claim a size of 120x100 Blocks what should be 12000. The result was negative aggain. The shown size is more than doubled and also highers its amount when Y diatance of point1 and point2 gets bigger.

**Comment by Darkilen** [comment]
Hello,
After a lot of test with @CloudeLecaw, we found where the issue come from.
Red message come from option `define-max-distance` in config.yml. He set his value to `12000`. That mean, between his 2 points, he need to have less than 12000 "blocks".
BUT when you try to show preview border ([here](https://github.com/FabioZumbi12/RedProtect/blob/9e4a85141d45f468f9161006498cffcadb1326b2/RedProtect-Spigot/src/main/java/br/net/fabiozumbi12/RedProtect/Bukkit/listeners/RPPlayerListener.java#L160)), you check if the distance SQUARED between the two points is less than the value defined in `define-max-distance`([here](https://github.com/FabioZumbi12/RedProtect/blob/9e4a85141d45f468f9161006498cffcadb1326b2/RedProtect-Spigot/src/main/java/br/net/fabiozumbi12/RedProtect/Bukkit/listeners/RPPlayerListener.java#L168))...

Well, i'm going to ask you something, what's the purpose of this non-skippable option (except by giving permission to override the limit) ?

I can make a pull request to fix it, if it's really necessary, otherwise, to remove it.

**Comment by FabioZumbi12** [comment]
Its just to avoid infinite loop and crash the server, since redprotect scan all fences one by one on claim, to check other regions, to check regions from same player, overriting...etc. Just set this to high values to avoid this option.

**Comment by CloudeLecaw** [comment]
Hello Fabio.


Our Problem is we dont want to allow Players to Claim "megabig" regions
our Players should be allow to Claim the 12000 area with the wandtool
this normaly would be a size of 100 x 120 blocks or 75 x 160..or simliar

Would it help to set: as a first workarround to set:
**define-max-distance: 999999**
and Limit the playersize with permission?
**redprotect.limit.blocks.12000** ?

**Comment by FabioZumbi12** [comment]
Exact! Btw, the valies is fixed now on latest dev build.
