### ISSUE TITLE
[BUG] Bad explosions protection 

### ISSUE THREAD

**Issue by daniorio** [FabioZumbi12/RedProtect#498]
**Describe the bug**
On my server i running two plugins - RedProtect and ExtraHardMode. But RedProtect Regions can't protect world from custom explosions from ExtraHardMode plugin. ExtraHardMode dynamite, creepers, blazes and others easy break private land.

**Server and plugins versions (please complete the following information):**
 - Server: Kcauldron/Thermos/Ultramine 1.7.10
 - Plugin Version: RedProtect-7.5.6-b163-Universal
 - Java Version: 8

**Comment by FabioZumbi12** [comment]
This is not a Redprotect issue since redprotect just listen for KCauldron (server api in general) events and not for specific mod events. The mods should hook into events correctly or the server api should allow event to be cancelled, but i think will never be fixed since KCauldron is not maintained and not updated anymore.
