### ISSUE TITLE
[BUG] Not work on 1.7.10 with guava

### ISSUE THREAD

**Issue by daniorio** [FabioZumbi12/RedProtect#521]
**Describe the bug**
Plugin don't work with this guava's version 

**Screenshots and LOGs**
![изображение](https://user-images.githubusercontent.com/42574494/64202369-a54b3b80-ce99-11e9-8a64-9adcfabf24d7.png)
Pls usen't guava10/com/google/*, use com/google/*

**Server and plugins versions**
 - Server: Kcauldron/Thermos/UltramineBukkit 1.7.10
 - Plugin Version: Latest(RedProtect-7.6.3-b270-Universal)
 - Java Version: Java 1.8

**Comment by FabioZumbi12** [comment]
As described on plugin home page, is not compatible with lower versions of guava. This is because some dependencies and i cant change this. Use this version with your 1.7.10 version: https://www.spigotmc.org/resources/redprotect-anti-grief-server-protection-region-management-1-7-1-14.15841/download?version=266312
