### ISSUE TITLE
[Suggestion] Player should be kicked from claim despite pet

### ISSUE THREAD

**Issue by ghost** [FabioZumbi12/RedProtect#632]
**Is your feature request related to a problem? Please describe.**
If a player is riding his pet and is on a foreign claim and someone kicks him with /rp kick <player> he will not be kicked. Only when he gets off his pet and the kick cool down is still active will he be kicked.

**Describe the solution you'd like**
It would therefore be good to include this. The pet plugin used is [SimplePets](https://www.spigotmc.org/resources/simplepets.14124/)

**Describe alternatives you've considered**
I can't think of any other option.

**Comment by Melvout** [comment]
Hi !

I'm adding that : Whenever you are on an entity ( minecart, boat, horse, pig and pet from other plugin ) the welcoming message when entering a claim is not displayed in the chat.

I'm saying that here because I think it is related to this issue.

Thanks.

**Comment by DakirDEV** [comment]
In the new RedProtect-7.7.2-b376-Universal the bug is unfortunately still present. If a player sits on a pet from the SimplePets plugin, he will not be kicked. He can still ride with his pet over the whole claim. Only when he dismounts, he will be kicked. Only with a normal entity like a self tamed pig or horse you get kicked.

**Comment by FabioZumbi12** [comment]
Yeah, i can fire only normal entity kick to do not need to hook indo various pet plugins :/
