### ISSUE TITLE
[BUG] Player can't teleport from region with "can-move" false

### ISSUE THREAD

**Issue by Krosta8** [FabioZumbi12/RedProtect#643]
**Describe the bug**
Player is in a region. Owner of the region change flag "can-move" to false. Player can't move, that's expected, but also can't teleport outside of the region (/home, /tpa, etc.. tried with CMI plugin, but I think, that is not related).

**To Reproduce**
1. Create region
2. Another player step into the region
3. Flag "can-move" change from true to false
4. Player without permissions can't teleport outside of the region.

**Expected behavior**
Player should be able to teleport out of the region or kick all non-members from the region, if this flag is set to true, but there could be problem with the kick, that it should kick them in a danger place (lava, etc..)

**Server and plugins versions (please complete the following information):**
 - Server: Mohist 1.12.2 (build 532)
 - Plugin Version: RedProtect-7.6.7-b325-Universal.jar
 - Java Version: Java 1.8

**Comment by FabioZumbi12** [comment]
This is intended. If cant move it cant teleport too

**Comment by Krosta8** [comment]
But the problem is with portals.
Player can go through portal from Nether to overworld and got stuck in Nether portal, can't do anything.

**Comment by CloudeLecaw** [comment]
Jup they get stuck, but Redprotect is doing no nothing wrong here. If your using nether portals on your server i suggest to l gibe your players permission in the gui to the portal flags portal-enter (allows entering portal on a zone for stangers) portal-exit (allow entering a portal if the exit leads into a region) and allow-create-portal (allow building Portals in Region and deny it if exit would be created in a region on the exit site)

**Comment by Krosta8** [comment]
Oh, so sorry, didn't know, that this flag can solve my problem. I set in config portal-exit=false and remove players permission to change this flag, so I can give them back permission for can-move flag and the problem with stuck in portal will never happen again.
Thanks! :)

**Comment by CloudeLecaw** [comment]
i recomment to define it in your enabled flags for the GUI - waht means its defined for there regons when new created or someone open the GUIflag in the region.
![Snag_b0169d](https://user-images.githubusercontent.com/12080017/85233909-37f99e80-b40a-11ea-98e6-b6d9b043d6a3.png)
you fine the flags here in the [wiki](https://github.com/FabioZumbi12/RedProtect/wiki/(05)-Region-Flags#admin-flags)
Since these are adminflags your dont need to give permission for this if you dont want your placers to change it.
if you want this then you nedd to define it in config, in the GUI (slot,icon, description,name)
give players the Permission
Permission: redprotect.flag.(flagname)  (so 3 permissions for the 3 adminsflags to become userflags)
then they are able to see the flags in the GUI and are allowed to change them in their regions.

**Comment by Krosta8** [comment]
Ok, good to know, thanks
