### ISSUE TITLE
some issues with bungeecord.

### ISSUE THREAD

**Issue by netherarts** [FabioZumbi12/RedProtect#68]
i have applied bungeecord yesterday. so i've some problem about red protect with bungeecord.

they have their skins, inventory properly, but red protect doesn't.

if i use a command '/rp info', it displays their uuid (ex : 59d776c3-5840-4997-8b81-f9f1701f7186 not nickname) and displays not owner of the residence.

i did bungeecord and ip_forwand set to true.

what should i do?

**Comment by FabioZumbi12** [comment]
This is because you changed from online mode to offline mode and causes player validation method, on online mode with uuids, and offline mode with names. Redprotect can only convert from names to uuid because we can get the uuid from name, but cant do the same with offline mode because the uuids is not the same of mojang. You need to convert or change the owners manually.

**Comment by netherarts** [comment]
how can i convert the oweners manually?

**Comment by Stuart74** [comment]
There are a few sites that can convert UUID to player names such as 

http://minecraft-techworld.com/uuid-lookup-tool

I also believe there is a spigot plugin that helps with it also use the below at your own risk but should work and probably better doing this locally and testing before putting it live.

https://www.spigotmc.org/resources/uuid-playername-save-file-converter.558/

**Comment by netherarts** [comment]
@Stuart74 oh thanks for your reply. so.. i never used before whatever standalone things. it is bukkit or plugin?

**Comment by Stuart74** [comment]
@netherarts I have never used the standalone one but it does show you how to use it.   Depending on how many players you need to convert the first option may be easier but more time consuming since you have to do it one at a time. I sure there are other UUID Conversion tools out there just have to google them and choose which ones work better for you.

**Comment by FabioZumbi12** [comment]
The best way is you re-add the player on your own regions. I will take a look if theres a way to get real UUIDs for offline servers, but this can take long time...

**Comment by FabioZumbi12** [comment]
I have added a method where my plugin will make requests to Mojang servers to get tha playernames from Legacy UUIDs.

MAKE A BACKUP of your all dabatase and test this version: https://github.com/FabioZumbi12/RedProtect/blob/master/release/RedProtect-6.5.9-b694.jar?raw=true

**Comment by netherarts** [comment]
@FabioZumbi12 Thanks for your reply and update! but i got some errors while server starting. https://github.com/FabioZumbi12/RedProtect/issues/71
