### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by aril3721** [FabioZumbi12/RedProtect#738]
I Dont Know Why. Redprotect make a  lagging for my server
![image](https://user-images.githubusercontent.com/67541360/106088557-c9777e80-6158-11eb-8008-e4f81923b4f8.png)
![image](https://user-images.githubusercontent.com/67541360/106088692-ffb4fe00-6158-11eb-956c-82ee9a92fea0.png)

I Dont Know How To Fix Pls Help Me :<

My Server
8 GB Ram
Paper 1.16.4 Latest Version

**Comment by CloudeLecaw** [comment]
So your problem is that u have to much mobs spawned i see

In Spigot/Paper Versions higher then 1.16.x this can accour, specially on server with many loaded chunks
a plugin like [`EntityTrackerFixer`](https://www.spigotmc.org/resources/entitytrackerfixer-fix-1-14-4-1-16-2-entitytick-lag.70902/) helps here to reduce the needed sources.

**Comment by aril3721** [comment]
ahhhh thanks
