### ISSUE TITLE
Mysql and pom.xml

### ISSUE THREAD

**Issue by sintaxcz** [FabioZumbi12/RedProtect#84]
ello i have problem with mysql configuration
file-type: mysql
db-name: mysql_4499
user-name: mysql_4499
user-pass: ****(hiden)****
host: mysql.hicoria.com

even i try it with ' ' and plugin cant connect in console i have
Redprotect: [ysql_4499_Megamodded] Theres was an error while connecting to Mysql database! RedProtect will try to connect again in 15 seconds. If still not connecting, check the DB

Megamodded is name of my server but i cant change name of my database becouse of my hosting not suporting change names how i force this plugin to connect only to mysql_4499 ? thanks for help

I found code in worldmysqlregionmanager.java
this.dbname = RPConfig.getString("mysql.db-name") + "_" + this.world.getName();

and i cant change it becouse pom.xml dont work and maven dont download dependencies

**Comment by FabioZumbi12** [comment]
Hello.
Other user have this same problem and maybe is because numbers in database name. Try to use only letters on db name (if you can).

**Comment by Stuart74** [comment]
Your database is by default blocks all external servers from modifying/creating databases they only allow these types of changes locally i only say that as i believe your game server is hosted on a seperate server than where you host minecraft,  since you have put your host as being host: mysql.hicoria.com  if your database is on the same server as your game server then all you need to put in host is localhost and it should connect regardless of numbers but it is good practice not to use numbers when creating databases. 

I suggest speaking to your provider and ask if the database and its tables are allowed to be altered/modified/created from an external server. As most if not all servers do not allow changes from an external server only from local for security reasons, and if they do they have  to modify there mysql config to allow that also, and you would also need to ensure that your IP from the game server is also placed on the allow list.

I know i had to modify it on my server that holds my database which is held on a seperate server to my game server and i had to run the below command in sql command line 

mysql> GRANT ALL ON database_name.* TO user@xx.xxx.xx.xx IDENTIFIED BY 'your_password';

xx.xxx.xx.xx being your game server ip address

you would also need to modify the bind-address on your mysql config which i would find the provider would not do. 

Also try http://www.canyouseeme.org/ to see if the port is open or closed as well it most likely will be closed.

Hope this helps but i can't see you fixing this anytime soon if your not in control of your sql database server. This is not a plugin bug but a hosting issue should refer this to your hosting provider.

**Comment by sintaxcz** [comment]
Hi no mysql server is on same host i have authme + prism + grief prevention all set on mysql without problems and i cant change name of mysql database becuse name is bounded with server hosting username

**Comment by FabioZumbi12** [comment]
I have rewrite all mysql code to use only on database for all regions and worlds. try the latest version and follow the instructions to move your old mysql thinks to new.
