### ISSUE TITLE
wrong heads icons in mob gui for animals and monster in 1.20.4[BUG] 

### ISSUE THREAD

**Issue by CloudeLecaw** [FabioZumbi12/RedProtect#856]
We have a problem with Redprotect after we changed to Paper 1.20.4 The GUI shows  Bones for all Animals and for Monsters only magma creames instead of the heads of the gui.  Also  the chat tells for both GUIs this line see i the screenshot.  The Console shows No errors.  We use Builld 437 on our Server 

![Snag_72b7a81](https://github.com/FabioZumbi12/RedProtect/assets/12080017/9322e2d9-6be7-41f5-8c0f-f56118d1c370)
![Snag_72c6937](https://github.com/FabioZumbi12/RedProtect/assets/12080017/b6f93799-2fc3-467f-bcc5-225a956bbbd8)
![Snag_72cce4a](https://github.com/FabioZumbi12/RedProtect/assets/12080017/97455b5b-3f3a-4e49-beda-664d5dc3ef17)

**Comment by Blueeyestar** [comment]
I can confirm that!!! Please fix it because the Gui with the heads is nicer and more comfortable!!

Thank you

**Comment by Blueeyestar** [comment]
Is there still support for Red Protect???

**Comment by Blueeyestar** [comment]
The problem still exists in 1.20.5!

**Comment by Blueeyestar** [comment]
The problem still exists in 1.20.6!

**Comment by FabioZumbi12** [comment]
Updating to 1.20.6 , a lot of block and potion types have changed their names, probably breaking the GUIs. Try the build from devbuild: http://host.areaz12server.net.br:8081/job/RedProtect/438/

**Comment by FabioZumbi12** [comment]
Ok, some type of mobs have changed, replaced or removed, making your flag guis broken, here the list:

MUSHROOM_COW > MOOSHROOM
SNOWMAN > SNOW_GOLEM
PIG_ZOMBIE > -REMOVED-

Download: http://host.areaz12server.net.br:8081/job/RedProtect/lastBuild/

**Comment by Blueeyestar** [comment]
> Ok, some type of mobs have changed, replaced or removed, making your flag guis broken, here the list:
> 
> MUSHROOM_COW > MOOSHROOM SNOWMAN > SNOW_GOLEM PIG_ZOMBIE > -REMOVED-
> 
> Download: http://host.areaz12server.net.br:8081/job/RedProtect/lastBuild/

Even with a freshly generated Red Protect version with build: 439, the error still exists and no heads can be seen. These should actually be fixed in a newly generated version, right??
The description:
--> Changed and added mob types for FlagMobGui, YOU NEED TO CHANGE IN YOUR FLAGGUI CONFIG FILE: MUSHROOM_COW > MOOSHROOM | SNOWMAN > SNOW_GOLEM | PIG_ZOMBIE > -REMOVED- -
Doesn't help me because there is no FlagMobGui, only a MobFlagGui.class but it is hard coded and I don't think that is what is meant.

**Comment by CloudeLecaw** [comment]
i was looking at the files but it seems like there is no MobFlagGui file nor a MobFlagGuiFlag setting in config.conf.
so where these chnages are located?

**Comment by Blueeyestar** [comment]
Unfortunately, Minecraft 1.21 is now online and there is still no fix for the problem. Very disappointing because I also wrote to the developer in Discord where I was skillfully ignored, although the problem is known and there is probably a solution... very unfortunate

**Comment by FabioZumbi12** [comment]
Hey, i found the solution, and for our surprise, the solution was not simple. 1.20 was not accepting in any way the old  head textures, but glading to an example plugin called HeadDrop, the fix is online and available for 1.20 and 1.21. You can download the build 440.

http://host.areaz12server.net.br:8081/job/RedProtect/lastBuild/

**Comment by Blueeyestar** [comment]
Super, thank you very much, the users have been waiting for this for a long time. Thank you for making the effort. It's nice to know that RP is working as usual again. Thank you

**Comment by CloudeLecaw** [comment]
> Hey, i found the solution, and for our surprise, the solution was not simple. 1.20 was not accepting in any way the old head textures, but glading to an example plugin called HeadDrop, the fix is online and available for 1.20 and 1.21. You can download the build 440.
> 
> http://host.areaz12server.net.br:8081/job/RedProtect/lastBuild/
Build 440 Solved the issue for us on 1.20.4   1.20.6 and also on 1.21
So The ticket can be closed :)
